Bookers/config/routes.rb
Rails.application.routes.draw do
	devise_for :users
    root :to => 'home#home'
    get '/home/about', to: 'home#about'
    get '/home', to: 'home#home'
	resources :users
	resources :books
end


# $ rails routes
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                      root GET    /                                                                                        home#home
#                home_about GET    /home/about(.:format)                                                                    home#about
#                      home GET    /home(.:format)                                                                          home#home
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#                     books GET    /books(.:format)                                                                         books#index
#                           POST   /books(.:format)                                                                         books#create
#                  new_book GET    /books/new(.:format)                                                                     books#new
#                 edit_book GET    /books/:id/edit(.:format)                                                                books#edit
#                      book GET    /books/:id(.:format)                                                                     books#show
#                           PATCH  /books/:id(.:format)                                                                     books#update
#                           PUT    /books/:id(.:format)                                                                     books#update
#                           DELETE /books/:id(.:format)                                                                     books#destroy
#                refile_app        /attachments                                                                             #<Refile::App app_file="/home/vagrant/.bundle/ruby/2.5.0/refile-46b4178654e6/lib/refile/app.rb">
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Bookers/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
  def home
  end
end

Bookers/app/helpers/home_helper.rb
module HomeHelper
end

Bookers/app/views/home/_header.html.erb
<%# <%= render "home/header" %>

<header class="navbar navbar-fixed-top navbar-inverse" >
	<div class="container">
		<div><p class="bookers_logo">Bookers</p></div>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
				<li class="nav_item"><%= link_to "Home", user_path(current_user), class: "glyphicon glyphicon-home text-muted home" %></li>
				<li class="nav_item"><%= link_to "Users", users_path, class: "glyphicon glyphicon-link text-muted users" %></li>
				<li class="nav_item"><%= link_to "Books", books_path, class: "glyphicon glyphicon-book text-muted books" %></li>
				<li class="nav_item"><%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out text-muted logout" %></li>
				<% else %>
				<li class="nav_item"><%= link_to "Home", home_path, class: "glyphicon glyphicon-home text-muted home" %></li>
				<li class="nav_item"><%= link_to "About", home_about_path, class: "glyphicon glyphicon-edit text-muted about" %></li>
				<li class="nav_item"><%= link_to "Sign up", new_user_registration_path, class: "glyphicon glyphicon-edit text-muted sign_up"%></li>
				<li class="nav_item"><%= link_to "login", user_session_path, class: "glyphicon glyphicon-log-in text-muted sign_in" %></li>
				<% end %>
			</ul>
	   </div>
</header>

<% if flash[:notice] %>
	<p class="flash"><%= flash[:notice] %>
</p>
<% end %>

Bookers/app/views/home/about.html.erb
<%= render "home/header" %>

<h1>Welcome to Bookers!</h1>

<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
	    </div>
	</div>
</footer>

Bookers/app/views/home/home.html.erb
<%= render "home/header" %>
<div class="body">
	<div class="container">
		<div class="row">
			<div class="top_message col-md-offset-3 col-md-6">
				<h1>welcome to <span class="glyphicon glyphicon-book"></span>Bookers</i>!!</h1>
				<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
				<p>you can share and exchange your opinions , inpressions , and emotions</p>
				<p>about varioius books!</p>
				<div class="btn_wrapper">
					<div class="row">
						<p><%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
					</div>
					<div class="row">
						<p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
	    </div>
	</div>
</footer>