Bookers/config/routes.rb
Rails.application.routes.draw do
	devise_for :users
    root :to => 'home#home'
    get '/home/about', to: 'home#about'
    get '/home', to: 'home#home'
	resources :users
	resources :books
end


# $ rails routes
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                      root GET    /                                                                                        home#home
#                home_about GET    /home/about(.:format)                                                                    home#about
#                      home GET    /home(.:format)                                                                          home#home
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#                     books GET    /books(.:format)                                                                         books#index
#                           POST   /books(.:format)                                                                         books#create
#                  new_book GET    /books/new(.:format)                                                                     books#new
#                 edit_book GET    /books/:id/edit(.:format)                                                                books#edit
#                      book GET    /books/:id(.:format)                                                                     books#show
#                           PATCH  /books/:id(.:format)                                                                     books#update
#                           PUT    /books/:id(.:format)                                                                     books#update
#                           DELETE /books/:id(.:format)                                                                     books#destroy
#                refile_app        /attachments                                                                             #<Refile::App app_file="/home/vagrant/.bundle/ruby/2.5.0/refile-46b4178654e6/lib/refile/app.rb">
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
  attachment :avatar_image

  validates :name, presence: true, length: 	{ in: 2..20 }
  validates :self_introduction_text, length: { maximum: 50 }
end

Bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!
	def index
		@book = Book.new
		@users = User.all
		# @books = Book.where(user_id: "")
		@user = current_user
	end

	def show
		@user = User.find(params[:id])
		@books = @user.books
		@newbook = Book.new
	end

	def edit
		if current_user != User.find(params[:id])
		   redirect_to user_path(current_user)
		end
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		   flash[:notice] = "update successfully!"
		   redirect_to user_path(current_user)
		else
			flash[:notice] = "error, update failed"
			redirect_to edit_user_path(current_user)
	    end
	end

	private
	def user_params
		params.require(:user).permit(:name, :avatar_image, :self_introduction_text)
	end
	def book_params
		params.require(:book).permit(:title, :opinion)
	end
end

Bookers/app/helpers/users_helper.rb
module UsersHelper
end

Bookers/app/views/users/_info.html.erb
<%#   <%= render "users/info" users: @owndata %>

<div class="col-xs-3">
	<h2>User info</h2>
	<div class="user-image">
		<%= attachment_image_tag @user, :avatar_image_id, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
	</div>
	<table class="table">
		<tbody>
			<tr>
				<th>name</th>
				<th><%= @user.name %></th>
			</tr>
			<tr>
				<th>introduction</th>
				<th><%= @user.self_introduction_text %></th>
			</tr>
		</tbody>
	</table>
	<div class="row">
		<%= link_to 'Update_icon', edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
	</div>
</div>

Bookers/app/views/users/edit.html.erb
<%= render "home/header" %>

<div class="container">

	<p id="notice"></p>

	<h2>User info</h2>
	<%= form_for(@user) do |f| %>

	<div class="field">
		<label for="user_name">Name</label>
		<%= f.text_field :name, class:"name" %>
	</div>

	<div class="field">
		<label for="user_image">Image</label>
		<%= f.attachment_field :avatar_image, class:"user_image" %>
	</div>

	<div class="field">
		<label for="user_introduction">Introduction</label>
		<%= f.text_area :self_introduction_text, class:"introduction" %>
	</div>

	<div class="actions">
		<%= f.submit "Update User" %>
	</div>
	<% end %>

</div>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
	    </div>
	</div>
</footer>

Bookers/app/views/users/index.html.erb
<%= render "home/header" %>
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<div class="user-image">
				<%= attachment_image_tag @user, :avatar_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
			</div>
			<table class="table">
				<tbody>
					<tr>
						<th class="col-xs-12">name</th>
						<th class="col-xs-12"><%= @user.name %></th>
					</tr>
					<tr>
						<th class="col-xs-12">introduction</th>
						<th class="col-xs-12"><%= @user.self_introduction_text %></th>
					</tr>
				</tbody>
			</table>
				<%= link_to '', edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>
			<h2>New book</h2>

			<% if @book.errors.any? %>
				<div id="error_explanation">
					<h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
					<ul>
						<% @book.errors.full_messages.each do |message| %>
						<li><%= message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

			<%= form_for(@book) do |f| %>
			<div class="field">
				<label class="book_title">Title</label>
				<%= f.text_field :title, class: "col-xs-12 book_title" %>
			</div>
			<div class="field">
				<label class="book_body">Opinion</label>
				<%= f.text_area :opinion, class: "col-xs-12 book_body" %>
			</div>

			<div class="actions">
				<%= f.submit 'Create Book', class: "col-xs-12 btn btn-primary" %>
			</div>
			<% end %>
	    </div>

	    <div class="col-xs-9">
			<h2>Users</h2>

			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody><% @users.each do |user| %>
					<tr>
						<td>
							<%= attachment_image_tag user, :avatar_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
						</td>
						<td><%= user.name %></td>
						<td><%= link_to "show", user_path(user.id), class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
        </div>
    </div>
</div>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
	    </div>
	</div>
</footer>

Bookers/app/views/users/show.html.erb
<%= render "home/header" %>
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<div class="user-image">
				<%= attachment_image_tag @user, :avatar_image, :fill, 60, 60,format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
			</div>
			<table class="table">
				<tbody>
					<tr>
						<th>name</th>
						<th><%= @user.name %></th>
					</tr>
					<tr>
						<th>introduction</th>
						<th><%= @user.self_introduction_text %></th>
					</tr>
				</tbody>
			</table>
			<div>
				<%= link_to '', edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>
			</div>
	        <div>
			<h2>New book</h2>

			<% if @newbook.errors.any? %>
				<div id="error_explanation">
					<h2><%= @newbook.errors.count %>件のエラーが発生しました。</h2>
					<ul>
						<% @newbook.errors.full_messages.each do |message| %>
						<li><%= message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
			<%= form_for(@newbook) do |f| %>
			<div class="field">
				<label for="book_title", class="col-xs-12">Title</label>
				<%= f.text_field :title, class: "book_title col-xs-12" %>
			</div>
			<div class="field">
				<label for="book_opinion", class="col-xs-12">Opinion</label>
				<%= f.text_area :opinion, class: "book_body col-xs-12" %>
			</div>

			<div class="actions">
				<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
			</div>
			<% end %>
		    </div>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody><% @books.each do |book| %>
					<tr>
						<td><%= link_to user_path(@user.id), class: "user_#{@user.id}" do %>
							<%= attachment_image_tag @user, :avatar_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
							<% end %></td>
						<td><%= link_to book_path(book.id), class: "book_#{book.id}" do%>
								<%= book.title %>
								<% end %>
						</td>
						<td><%= book.opinion %></td>
						<td></td>
						<td></td>
					</tr>
						<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
	    </div>
	</div>
</footer>