Bookers/config/routes.rb
Rails.application.routes.draw do
	devise_for :users
    root :to => 'home#home'
    get '/home/about', to: 'home#about'
    get '/home', to: 'home#home'
	resources :users
	resources :books
end


# $ rails routes
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                      root GET    /                                                                                        home#home
#                home_about GET    /home/about(.:format)                                                                    home#about
#                      home GET    /home(.:format)                                                                          home#home
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                 edit_user GET    /users/:id/edit(.:format)                                                                users#edit
#                      user GET    /users/:id(.:format)                                                                     users#show
#                           PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                           DELETE /users/:id(.:format)                                                                     users#destroy
#                     books GET    /books(.:format)                                                                         books#index
#                           POST   /books(.:format)                                                                         books#create
#                  new_book GET    /books/new(.:format)                                                                     books#new
#                 edit_book GET    /books/:id/edit(.:format)                                                                books#edit
#                      book GET    /books/:id(.:format)                                                                     books#show
#                           PATCH  /books/:id(.:format)                                                                     books#update
#                           PUT    /books/:id(.:format)                                                                     books#update
#                           DELETE /books/:id(.:format)                                                                     books#destroy
#                refile_app        /attachments                                                                             #<Refile::App app_file="/home/vagrant/.bundle/ruby/2.5.0/refile-46b4178654e6/lib/refile/app.rb">
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Bookers/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	 validates :title, presence: true
     validates :opinion, presence: true, length: { maximum: 200 }
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!

	def index
		@books = Book.all
		@book = Book.new
		@user = current_user
	end

	def show
		@newbook = Book.new
		@book = Book.find(params[:id])
		@user = @book.user
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:notice] = "Update successfully!"
			redirect_to book_path(@book.id)
		else
			flash[:notice] = "error, Update failed"
			redirect_to edit_book_path(@book.id)
		end
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = "save successfully!"
			redirect_to book_path(@book.id)
		else
			flash[:notice] = "error, save failed"
			@books = Book.all
			@newbook = Book.new
			@user = current_user
			render :index
		end
	end

	def destroy
		book = Book.find(params[:id])

		if book.destroy
			flash[:notice] = "destroy successfully!"
			redirect_to books_path
		else
			flash[:notice] = "destroy failed"
			redirect_to books_path
		end
	end

	private

	def book_params
		params.require(:book).permit(:title, :opinion)
	end

	def user_params
		params.require(:user).permit(:name, :avatar_image_id, :self_introduction_text)
	end
end

Bookers/app/helpers/books_helper.rb
module BooksHelper
end

Bookers/app/views/books/_post.html.erb
<%#  <% render "books/post", books: @book %>
<%#@bookをbooksとして渡している↑%>

<div>
    <h2>New book</h2>

    <%= form_for(books) do |book| %>
  <div class="field row">
    <label for="book_title", class="col-xs-12 book_title">Title</label>
     <%= book.text_field :title %>
  </div>
  <div class="field row">
    <label for="book_opinion", class="col-xs-12 book_body">Opinion</label>
    <%= book.text_area :opinion %>
  </div>

  <div class="actions row">
    <%= book.submit 'Create Book' %>
  </div>
<% end %>
</div>

Bookers/app/views/books/edit.html.erb
<%= render "home/header" %>

<div class="container">

	<div class="row">

		<div class="col-md-6 col-md-offset-3">

			<h1>Editing Book</h1>

			<%= form_for(@book) do |f| %>

			<h4>Title</h4>

			<%= f.text_field :title, class:"book_title" %>

			<h4>Opinion</h4>

			<%= f.text_area :opinion, class:"book_body" %>

			<div><%= f.submit 'Update Book', class: "btn btn-primary" %></div>

			<% end %>

			<%= link_to "Show", book_path(@book.id), class: "book_#{@book.id}" %>

			<%= link_to "Back", books_path, class:"back", class: "back" %>
		</div>
	</div>
</div>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
	    </div>
	</div>
</footer>

Bookers/app/views/books/index.html.erb
<%= render "home/header" %>
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<div class="user-image">
				<%= attachment_image_tag @user, :avatar_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
			</div>
			<table class="table">
				<tbody>
					<tr>
						<th class="col-xs-12">name</th>
						<th class="col-xs-12"><%= @user.name %></th>
					</tr>
					<tr>
						<th class="col-xs-12">introduction</th>
						<th class="col-xs-12"><%= @user.self_introduction_text %></th>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<%= link_to '', edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>
			</div>

			<div>
				<h2>New book</h2>
				<% if @book.errors.any? %>
					<div id="error_explanation">
							<h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
							<ul>
								<% @book.errors.full_messages.each do |message| %>
								<li><%= message %></li>
								<% end %>
							</ul>
					</div>
				<% end %>
				<%= form_for(@book) do |f| %>

				<div class="field row">
					<label for="book_title", class="col-xs-12 book_title">Title</label>
					<%= f.text_field :title, class: "col-xs-12 book_title" %>
				</div>
				<div class="field row">
					<label for="book_opinion", class="col-xs-12 book_body">Opinion</label>
					<%= f.text_area :opinion, class: "col-xs-12 book_body" %>
				</div>
				<div class="actions row">
					<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
				</div>
				<% end %>
			</div>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody><% @books.each do |book| %>
					<tr>
						<td><%= link_to user_path(book.user_id), class: "user_#{book.id}" do %>
							<%= attachment_image_tag book.user, :avatar_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
							<% end %>
						</td>
						<td><%= link_to book_path(book.id), class: "book_#{book.id}" do %>
							<%= book.title %>
							<% end %>
						</td>
						<td><%= book.opinion %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
		</div>
	</div>
</footer>

Bookers/app/views/books/show.html.erb
<%= render "home/header" %>
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<div class="user-image">
				<%= attachment_image_tag @user, :avatar_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
			</div>
			<table class="table">
				<tbody>
					<tr>
						<th>name</th>
						<th><%= @user.name %></th>
					</tr>
					<tr>
						<th>introduction</th>
						<th><%= @user.self_introduction_text %></th>
					</tr>
				</tbody>
			</table>
			<div>
				<%= link_to '', edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_3589 edit_user_#{@user.id}" %>
			</div>

			<h2>New book</h2>
			<% if @newbook.errors.any? %>
			<div id="error_explanation">
				<h2><%= @newbook.errors.count %>件のエラーが発生しました。</h2>
				<ul>
					<% @newbook.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
					<% end %>
				</ul>
				<%= form_for(@newbook) do |f| %>
				<div class="field">
					<label for="book_title", class="col-xs-12 book_title">Title</label>
					<%= f.text_field :title, class: "col-xs-12 book_title" %>
				</div>
				<div class="field">
					<label for="book_opinion", class="col-xs-12 book_body">Opinion</label>
					<%= f.text_area :opinion, class: "col-xs-12 book_body" %>
				</div>
				<div class="actions">
					<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
				</div>
				<% end %>

			</div>
			<div class="col-xs-9">
				<h2>Book detail</h2>
				<table class="table">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th class="colspan=3"></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><%= link_to user_path(@book.user_id), class: "user_#{@book.id}" do %>
								<%= attachment_image_tag @book.user, :avatar_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
								<% @book.user.name %>
								<% end %>
							</td>
							<td><%= link_to book_path(@book.id), class: "book_#{@book.id}" do%>
								<%= @book.title %>
								<% end %>
							</td>
							<td><%= @book.opinion %></td>
							<td>
								<% if @book.user == current_user %>
								<%= link_to "Edit", edit_book_path(@book.id), class: "edit_#{@book.id} btn-sm btn-success" %>
								<% end %>
							</td>
							<td>
								<% if @book.user == current_user %>
								<%= link_to "Destroy", book_path(@book.id), class: "destroy_#{@book.id} btn-sm btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>
								<% end %>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-xs-3 col-xs-offset-9">
					<p>CopyRight Infratop.inc</p>
				</div>
			</div>
		</div>
	</footer>